services:
  db:
    image: postgres:15
    container_name: chat_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-doc
    ports:
      - 5431:5431
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d chat_db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


  chat:
    build:
      context: .
    container_name: chat_app
    env_file:
      - .env-doc
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000


volumes:
 postgresdata:
